import Footer from './components/Footer';
import Header from './components/Header'
import './globals.css';

import { Mulish } from 'next/font/google'

const mulish = Mulish({
  weight: ['200','300','400','500','600','700','800',],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'MovieTime',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className} >
      <body>
        <Header />
        <div>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}
